### PR TITLE
Make functions

### PR DESCRIPTION
**Pull request by preposthuman**
My primary reason for turning large blocks of code into functions is so that you can read and understand the functions (as they are self-contained), and when you read down to the function call, you already know that it's valid.

### CODE REVIEW

**Comment by preposthuman** [comment]
The next step is moving all the functions into a common file so you don't have to repeat code.

**Comment by khalwat** [comment]
ooooooh, I definitely like this refactoring. Should I wait until you are able to tackle moving the functions into a common file, or just do it now?

**Comment by preposthuman** [comment]
You should do it now, so that I can sync that back, and start work on the next piece.
I'm trying to do each PR in a self-contained manner, so that the changes are small enough that you can see what they are and how they work.

**Comment by khalwat** [comment]
aaaagh, I forgot to do this! Are you still here @preposthuman ?

**Comment by khalwat** [comment]
Great, sorry about that. I  meant to take the time to make sure I tested all of this, and then I forgot about the PR. Apologies.

**Comment by khalwat** [comment]
Tagged & released! https://github.com/nystudio107/craft-scripts/releases/tag/1.2.8

Thanks again @preposthuman

**Comment by preposthuman** [comment]
BTW, do you want me to make PRs against a branch other than master?

**Comment by khalwat** [comment]
Yeah, if you don't mind doing them against `develop` that'd be great -- but it's not a big deal for me to switch them. Either way, I'm thankful for your help!

**Pull request merged**
