### PR TITLE
Improve bash scripts

### PR DESCRIPTION
**Pull request by preposthuman**
Making style more consistent

### CODE REVIEW

**Comment by khalwat** [comment]
Thanks @preposthuman this is great! I assume the `[` -> `[[` is because of http://mywiki.wooledge.org/BashFAQ/031 ?

**Comment by preposthuman** [comment]
Yes, mostly because if you always default to `[[]]`, then you'll never be unpleasantly surprised by unexpected behavior. It also has all those extra test modes.

**Comment by preposthuman** [comment]
Also, I've got plenty of bigger refactors in mind, if you're interested. I just wanted to get the easy stylistic changes done first.

**Comment by khalwat** [comment]
Let me merge and QA test this first, but yeah absolutely I'm totally open to a more complete refactoring.

**Comment by khalwat** [comment]
Thanks again!

**Pull request merged**
